export class Chatbot {
    constructor(options) {
        this.container = options.container;
        this.window = options.window;
        this.messagesContainer = options.messagesContainer;
        this.input = options.input;
        this.sendBtn = options.sendBtn;
        this.toggleBtn = options.toggleBtn;
        this.closeBtn = options.closeBtn;
        this.getApiKey = options.getApiKey;
        this.getSchemaSummary = options.getSchemaSummary;
        this.onRunQuery = options.onRunQuery;

        this.chatHistory = [];
        this.bindEvents();
    }

    bindEvents() {
        this.toggleBtn.addEventListener('click', () => this.toggleWindow());
        this.closeBtn.addEventListener('click', () => this.toggleWindow(false));

        this.sendBtn.addEventListener('click', () => this.handleSend());

        this.input.addEventListener('keydown', (e) => {
            if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                this.handleSend();
            }
        });
    }

    toggleWindow(force) {
        if (typeof force === 'boolean') {
            if (force) {
                this.window.classList.remove('hidden');
            } else {
                this.window.classList.add('hidden');
            }
        } else {
            this.window.classList.toggle('hidden');
        }

        if (!this.window.classList.contains('hidden')) {
            this.input.focus();
        }
    }

    async handleSend() {
        const text = this.input.value.trim();
        if (!text) return;

        const apiKey = this.getApiKey();
        if (!apiKey) {
            this.addMessage('assistant', 'Please enter your Google Gemini API key in the "Headers & Variables" drawer to use the chatbot.');
            return;
        }

        this.input.value = '';
        this.addMessage('user', text);

        // Add loading indicator
        const loadingId = this.addLoadingIndicator();
        this.scrollToBottom();

        try {
            const response = await this.callGeminiAPI(text, apiKey);
            this.removeMessage(loadingId);
            this.addMessage('assistant', response);
        } catch (error) {
            this.removeMessage(loadingId);
            this.addMessage('assistant', `Error: ${error.message}`);
        }
    }

    async callGeminiAPI(message, apiKey) {
        const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;

        // Initialize history with system prompt if empty
        if (this.chatHistory.length === 0) {
            let schemaSummary = "No schema data available.";
            try {
                if (this.getSchemaSummary) {
                    schemaSummary = await this.getSchemaSummary();
                }
            } catch (e) {
                console.warn("Failed to get schema summary for chatbot context", e);
            }

            const systemPrompt = `You are a helpful AI assistant for the Eurex GraphQL API Explorer.
Your job is to help the user understand the API, explain the schema, and write valid GraphQL queries for them based on their requests.
When you provide a GraphQL query, ALWAYS wrap it in markdown code blocks like this:
\`\`\`graphql
query {
  ...
}
\`\`\`
Here is a summary of the current GraphQL schema for your reference:
${schemaSummary}

Be concise and direct in your answers.`;

            this.chatHistory.push({
                role: "user",
                parts: [{ text: systemPrompt }]
            });
            this.chatHistory.push({
                role: "model",
                parts: [{ text: "Understood. I am ready to help with the Eurex GraphQL API." }]
            });
        }

        this.chatHistory.push({
            role: "user",
            parts: [{ text: message }]
        });

        const requestBody = {
            contents: this.chatHistory
        };

        const response = await fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(requestBody)
        });

        if (!response.ok) {
            const errorData = await response.json();
            throw new Error(errorData.error?.message || 'Failed to communicate with the Gemini API');
        }

        const data = await response.json();

        if (data.candidates && data.candidates.length > 0) {
            const replyText = data.candidates[0].content.parts[0].text;

            // Save model reply to history
            this.chatHistory.push({
                role: "model",
                parts: [{ text: replyText }]
            });

            return replyText;
        } else {
            throw new Error('No response generated by the model.');
        }
    }

    addMessage(role, text) {
        const msgDiv = document.createElement('div');
        msgDiv.className = `chat-message ${role}`;

        if (role === 'assistant') {
            // Very simple markdown parsing for code blocks using regex
            // Split by ```graphql ... ``` or ``` ... ```
            const parts = text.split(/```(?:graphql)?\n([\s\S]*?)```/g);

            for (let i = 0; i < parts.length; i++) {
                if (i % 2 === 0) {
                    // Regular text
                    if (parts[i].trim()) {
                        // Convert newlines to br
                        const lines = parts[i].split('\n');
                        for (let j=0; j<lines.length; j++) {
                            msgDiv.appendChild(document.createTextNode(lines[j]));
                            if (j < lines.length - 1) {
                                msgDiv.appendChild(document.createElement('br'));
                            }
                        }
                    }
                } else {
                    // Code block
                    const pre = document.createElement('pre');
                    const codeEl = document.createElement('code');
                    codeEl.textContent = parts[i].trim();
                    pre.appendChild(codeEl);
                    msgDiv.appendChild(pre);

                    const runBtn = document.createElement('button');
                    runBtn.className = 'run-query-btn';

                    // Add feather icon placeholder
                    const iconI = document.createElement('i');
                    iconI.setAttribute('data-feather', 'play');
                    iconI.style.width = '12px';
                    iconI.style.height = '12px';

                    runBtn.appendChild(iconI);
                    runBtn.appendChild(document.createTextNode(' Run this query'));

                    runBtn.onclick = () => {
                        if (this.onRunQuery) {
                            this.onRunQuery(parts[i].trim());
                        }
                    };
                    msgDiv.appendChild(runBtn);
                }
            }

        } else {
            // User message, plain text
            msgDiv.textContent = text;
        }

        this.messagesContainer.appendChild(msgDiv);

        if (window.feather) {
            window.feather.replace();
        }

        this.scrollToBottom();
    }

    addLoadingIndicator() {
        const id = 'loading-' + Date.now();
        const msgDiv = document.createElement('div');
        msgDiv.id = id;
        msgDiv.className = 'chatbot-loading';
        msgDiv.innerHTML = `
            <div class="chatbot-loading-dot"></div>
            <div class="chatbot-loading-dot"></div>
            <div class="chatbot-loading-dot"></div>
        `;
        this.messagesContainer.appendChild(msgDiv);
        this.scrollToBottom();
        return id;
    }

    removeMessage(id) {
        const el = document.getElementById(id);
        if (el) {
            el.remove();
        }
    }

    scrollToBottom() {
        this.messagesContainer.scrollTop = this.messagesContainer.scrollHeight;
    }
}
